# D-Trust Provider Configuration Example
# This file shows how to configure D-Trust QES provider for Germany

# QES Platform API connection
api_url: https://api.qes-platform.com/v1
tenant_id: your-tenant-id
api_key: your-api-key

# Provider configurations
providers:
  dtrust-de:
    # Provider identification
    name: dtrust-de
    type: dtrust
    country: DE
    environment: production  # or "test" for sandbox
    enabled: true
    
    # D-Trust endpoints
    endpoints:
      eidas: https://www.d-trust.net/eidas
      signature: https://api.d-trust.net/qes
      revocation: https://crl.d-trust.net
      
    # Client certificate authentication
    client_cert_path: /etc/ssl/certs/dtrust-client.crt
    client_key_path: /etc/ssl/private/dtrust-client.key
    ca_cert_path: /etc/ssl/certs/dtrust-ca.crt
    
    # D-Trust specific settings
    config:
      # eIDAS level required
      eidas_level: HIGH
      
      # Allowed authentication methods
      auth_methods:
        - PERSONAL_ID_CARD
        - QUALIFIED_CERTIFICATE
        - MOBILE_ID
      
      # Certificate policies
      certificate_policies:
        - "1.3.6.1.4.1.7879.13.24"  # D-Trust QES policy
        - "1.3.6.1.4.1.7879.13.25"  # D-Trust QSeal policy
        
      # Signature settings
      signature:
        hash_algorithm: SHA256
        signature_algorithm: RSA-PSS
        timestamp_required: true
        ltv_enabled: true
        
      # Certificate request settings
      certificate:
        key_length: 3072  # German standards recommend 3072+ bits
        validity_period: 365
        include_qcstatements: true
        
      # User identification requirements
      identification:
        require_personal_id: true
        require_address_verification: true
        require_photo_id: true
        
      # Organization settings
      organization:
        request_org_certificates: true
        require_trade_register: true
        allowed_org_types:
          - GMBH
          - AG
          - EINZELUNTERNEHMEN
          - VEREIN

# Global settings
settings:
  default_signature_format: PAdES-LTA
  timeout: 90s  # Longer timeout for eIDAS operations
  
  # Germany-specific settings
  locale: de-DE
  timezone: Europe/Berlin
  
  # eIDAS integration settings
  eidas:
    # Node configuration
    node_country: DE
    node_url: https://eidasnode.d-trust.net
    
    # Metadata settings
    metadata_url: https://eidasnode.d-trust.net/metadata
    metadata_signing_cert: /etc/ssl/certs/eidas-metadata.crt
    
    # Security settings
    encryption_required: true
    signature_required: true
    
    # Attribute requirements
    required_attributes:
      - PersonIdentifier
      - FamilyName
      - FirstName
      - DateOfBirth
      
    optional_attributes:
      - PlaceOfBirth
      - CurrentAddress
      - Gender
      
  # D-Trust specific settings
  dtrust:
    # API configuration
    api_version: v2
    max_retries: 3
    retry_delay: 5s
    
    # Certificate validation
    validate_certificate_chain: true
    check_revocation_status: true
    
    # Compliance settings
    bsi_compliant: true  # BSI TR-03109 compliance
    common_criteria: true  # Common Criteria EAL4+